version: "3.8"

services:
  ledius-crypto-bridge:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    container_name: ledius-crypto-bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./node_modules:/node_modules
    environment:
      - MODE=dev
    ports:
      - "3000:3000"

  ledius-crypto-bridge-postgres:
    image: postgres:12.3-alpine
    container_name: ledius-crypto-bridge-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  ledius-crypto-bridge-bitcoin:
    container_name: ledius-crypto-bridge-bitcoin
    build:
      context: ./bitcoin
      dockerfile: docker/Dockerfile
    volumes:
      - ./bitcoin/var/testnet3:/root/.bitcoin/testnet3
    ports:
      - "18332:18332"
