version: "3.8"

networks:
  ledius:
    external: true

services:
  ledius-crypto-bridge:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    container_name: ledius-crypto-bridge
    env_file:
      - .env
    environment:
      - MODE=prod
      - VIRTUAL_HOST=crypto-bridge-dev.ledius.ru,admin-sipex.ledius.space
      - VIRTUAL_PATH=/api
      - VIRTUAL_PORT=3000
    networks:
      - ledius

  sipex-core-redis:
    image: redis:6
    container_name: sipex-core-redis
    networks:
      - ledius
