version: "3.8"

networks:
  multichain-wallets:
    external: true

services:
  multichain-wallets:
    build: .
    container_name: multichain-wallets
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    environment:
      - MODE=dev
    ports:
      - "3000:3000"
    networks:
      - multichain-wallets

  multichain-wallets-postgres:
    image: postgres:14
    container_name: multichain-wallets-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - multichain-wallets
