apiVersion: batch/v1
kind: Job
metadata:
  name: crypto-bridge-migrations
spec:
  template:
    spec:
      containers:
        - name: crypto-bridge
          image: registry.gitlab.com/devsinglesly/crypto-bridge:develop
          imagePullPolicy: "Always"
          command: ["npx", "typeorm", "--config", "ormconfig.env.js", "migration:run"]
          envFrom:
            - configMapRef:
                name: crypto-bridge
      restartPolicy: Never
  backoffLimit: 4
  completions: 1
