apiVersion: batch/v1
kind: Job
metadata:
  name: ledius-token-migrations
spec:
  template:
    spec:
      containers:
        - name: ledius-token
          image: registry.gitlab.com/ledius.com/lds-token:main
          imagePullPolicy: "Always"
          command: ["npx", "typeorm", "--config", "ormconfig.env.js", "migration:run"]
          envFrom:
            - configMapRef:
                name: ledius-token.production
            - configMapRef:
                name: db.cert
      restartPolicy: Never
  backoffLimit: 4
  completions: 1
