apiVersion: batch/v1
kind: Job
metadata:
  name: crypto-bridge-migrations
spec:
  template:
    spec:
      containers:
        - name: crypto-bridge
          image: registry-intl.eu-central-1.aliyuncs.com/coins2prod/crypto-bridge:main
          imagePullPolicy: "Always"
          command: ["npx", "typeorm", "--config", "ormconfig.env.js", "migration:run"]
          envFrom:
            - configMapRef:
                name: crypto-bridge
      restartPolicy: Never
      imagePullSecrets:
        - name: alibaba
  backoffLimit: 4
  completions: 1
