version: '3.9'

networks:
  multichain-wallets:

services:
  multichain-wallets:
    image: devsinglesly/multichain-wallets
    hostname: multichain-wallets
    container_name: multichain-wallets
    env_file:
      - .env
    environment:
      - CIPHER_PASSWORD=${CIPHER_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "3000:3000"
    networks:
      - multichain-wallets

  multichain-wallets-postgres:
    image: postgres:14
    hostname: multichain-wallets-postgres
    container_name: multichain-wallets-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - multichain-wallets
