export enum LocalEnvPathEnum {
  // MICROSERVICE DEFINITION
  APP_NAME = 'APP_NAME',

  // APPLICATION CONFIG
  CIPHER_PASSWORD = 'CIPHER_PASSWORD',

  // DATABASE PATHS
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',

  // BITCOIN NETWORK
  BTC_RPC_AUTH_USERNAME = 'BTC_RPC_AUTH_USERNAME',
  BTC_RPC_AUTH_PASSWORD = 'BTC_RPC_AUTH_PASSWORD',
  BTC_RPC_BASE_URL = 'BTC_RPC_BASE_URL',

  // ETHEREUM NETWORK
  ETH_RPC_BASE_URL = 'ETH_RPC_BASE_URL',

  // TRON NETWORK
  TRON_RPC_BASE_URL = 'TRON_RPC_BASE_URL',
}
