export enum LocalEnvPathEnum {
  // MICROSERVICE DEFINITION
  APP_NAME = 'APP_NAME',
  APP_URL = 'APP_URL',
  ADMIN_ADDRESSES = 'ADMIN_ADDRESSES',

  JWT_SECRET = 'JWT_SECRET',

  // APPLICATION CONFIG
  CIPHER_PASSWORD = 'CIPHER_PASSWORD',

  // DATABASE PATHS
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',
}
