export enum LocalEnvPathEnum {
  // APPLICATION CONFIG
  CIPHER_PASSWORD = 'CIPHER_PASSWORD',

  // DATABASE PATHS
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',

  MIGRATIONS_RUN = 'MIGRATIONS_RUN',
}
