export enum LocalEnvPathEnum {
  // MICROSERVICE DEFINITION
  APP_NAME = 'APP_NAME',
  APP_URL = 'APP_URL',
  ADMIN_ADDRESSES = 'ADMIN_ADDRESSES',

  JWT_SECRET = 'JWT_SECRET',

  // APPLICATION CONFIG
  CIPHER_PASSWORD = 'CIPHER_PASSWORD',

  // DATABASE PATHS
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  // EPAY
  EPAY_API_KEY = 'EPAY_API_KEY',
  EPAY_BASE_URL = 'EPAY_BASE_URL',

  // TINKOFF
  TINKOFF_ACQUIRING_BASE_URL = 'TINKOFF_ACQUIRING_BASE_URL',
  TINKOFF_ACQUIRING_TERMINAL_KEY = 'TINKOFF_ACQUIRING_TERMINAL_KEY',
}
