export const WebErrorsEnum = {
  INTERNAL_ERROR: 1,

  PERMISSION_DENIED: 2,
  UNAUTHORIZED: 21,

  INVALID_ARGUMENT: 3,
  INVALID_AMOUNT_PROVIDED: 31,

  NOT_FOUND: 4,

  REQUIRED_ACCOUNT_ACTIVATION_TRX: 5,

  // Domain errors
  DOMAIN_ERROR: 6,
  INSUFFICIENT_FUNDS: 61,
};
