name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:
    environment: production
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
    
      - name: Login in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --tag devsinglesly:${{ GITHUB_REF_NAME }}

      - name: Push in to Docker Hub
        run: docker push devsinglesly:${{ GITHUB_REF_NAME }}
